# for point_cloud_color_detector
TOLERANCE: 0.2
HIGHEST_TARGET_Y: 10.0
LOWEREST_TARGET_Y: -10.0
MIN_CLUSTER_SIZE: 5
MAX_CLUSTER_SIZE: 2000
ONLY_PUBLISH_MASK_POINTS: false
PUBLISH_TARGET_POINTS: false

# for image_color_detector
ONLY_PUBLISH_MASK_IMAGE: false
PUBLISH_TARGET_IMAGE: false

# for both
LOWER_RED_H: 150
LOWER_RED_S: 150
LOWER_RED_V: 200
UPPER_RED_H: 190
UPPER_RED_S: 255
UPPER_RED_V: 255

LOWER_BLUE_H: 95
LOWER_BLUE_S: 210
LOWER_BLUE_V: 40
UPPER_BLUE_H: 105
UPPER_BLUE_S: 255
UPPER_BLUE_V: 110

LOWER_YELLOW_H: 20
LOWER_YELLOW_S: 90
LOWER_YELLOW_V: 115
UPPER_YELLOW_H: 30
UPPER_YELLOW_S: 160
UPPER_YELLOW_V: 255

LOWER_GOLD_H: 15
LOWER_GOLD_S: 160
LOWER_GOLD_V: 120
UPPER_GOLD_H: 25
UPPER_GOLD_S: 255
UPPER_GOLD_V: 200

LOWER_BLACK_H: 75
LOWER_BLACK_S: 100
LOWER_BLACK_V: 0
UPPER_BLACK_H: 110
UPPER_BLACK_S: 192
UPPER_BLACK_V: 66

LOWER_GREEN_H: 60
LOWER_GREEN_S: 100
LOWER_GREEN_V: 50
UPPER_GREEN_H: 100
UPPER_GREEN_S: 230
UPPER_GREEN_V: 100

LOWER_WHITE_H: 5
LOWER_WHITE_S: 5
LOWER_WHITE_V: 245
UPPER_WHITE_H: 25
UPPER_WHITE_S: 25
UPPER_WHITE_V: 255