# for point_cloud_color_detector
TOLERANCE: 0.2
HIGHEST_TARGET_Y: 10.0
LOWEREST_TARGET_Y: -10.0

# for image_color_detector

# for both
MIN_CLUSTER_SIZE: 5
MAX_CLUSTER_SIZE: 500
ONLY_PUBLISH_MASK_POINTS: false
PUBLISH_TARGET_POINTS: false

LOWER_RED_H: 130
LOWER_RED_S: 180
LOWER_RED_V: 80
UPPER_RED_H: 180
UPPER_RED_S: 230
UPPER_RED_V: 180

LOWER_BLUE_H: 95
LOWER_BLUE_S: 210
LOWER_BLUE_V: 40
UPPER_BLUE_H: 110
UPPER_BLUE_S: 255
UPPER_BLUE_V: 180

LOWER_YELLOW_H: 20
LOWER_YELLOW_S: 120
LOWER_YELLOW_V: 90
UPPER_YELLOW_H: 40
UPPER_YELLOW_S: 210
UPPER_YELLOW_V: 255

LOWER_GREEN_H: 60
LOWER_GREEN_S: 100
LOWER_GREEN_V: 50
UPPER_GREEN_H: 100
UPPER_GREEN_S: 230
UPPER_GREEN_V: 100
