# for point_cloud_color_detector
TOLERANCE: 0.2
HIGHEST_TARGET_Y: 0.70
LOWEREST_TARGET_Y: 0.00

# for image_color_detector

# for both
MIN_CLUSTER_SIZE: 10
MAX_CLUSTER_SIZE: 500
ONLY_PUBLISH_MASK_POINTS: false
PUBLISH_TARGET_POINTS: false

LOWER_RED_H: 130
LOWER_RED_S: 180
LOWER_RED_V: 80
UPPER_RED_H: 180
UPPER_RED_S: 230
UPPER_RED_V: 180

LOWER_BLUE_H: 95
LOWER_BLUE_S: 210
LOWER_BLUE_V: 40
UPPER_BLUE_H: 110
UPPER_BLUE_S: 255
UPPER_BLUE_V: 180

LOWER_YELLOW_H: 20
LOWER_YELLOW_S: 120
LOWER_YELLOW_V: 90
UPPER_YELLOW_H: 40
UPPER_YELLOW_S: 210
UPPER_YELLOW_V: 255

LOWER_GREEN_H: 60
LOWER_GREEN_S: 100
LOWER_GREEN_V: 50
UPPER_GREEN_H: 100
UPPER_GREEN_S: 230
UPPER_GREEN_V: 100

LOWER_ORANGE_H: 10
LOWER_ORANGE_S: 80
LOWER_ORANGE_V: 120
UPPER_ORANGE_H: 20
UPPER_ORANGE_S: 200
UPPER_ORANGE_V: 200

LOWER_PURPLE_H: 110
LOWER_PURPLE_S: 80
LOWER_PURPLE_V: 40
UPPER_PURPLE_H: 150
UPPER_PURPLE_S: 230
UPPER_PURPLE_V: 100
