ROOMBA6_LOWER_RED_H: 130
ROOMBA6_LOWER_RED_S: 180
ROOMBA6_LOWER_RED_V: 80
ROOMBA6_UPPER_RED_H: 180
ROOMBA6_UPPER_RED_S: 230
ROOMBA6_UPPER_RED_V: 180
ROOMBA6_LOWER_BLUE_H: 95
ROOMBA6_LOWER_BLUE_S: 210
ROOMBA6_LOWER_BLUE_V: 40
ROOMBA6_UPPER_BLUE_H: 110
ROOMBA6_UPPER_BLUE_S: 255
ROOMBA6_UPPER_BLUE_V: 180
ROOMBA6_LOWER_YELLOW_H: 20
ROOMBA6_LOWER_YELLOW_S: 120
ROOMBA6_LOWER_YELLOW_V: 90
ROOMBA6_UPPER_YELLOW_H: 40
ROOMBA6_UPPER_YELLOW_S: 210
ROOMBA6_UPPER_YELLOW_V: 255
ROOMBA6_LOWER_GREEN_H: 60
ROOMBA6_LOWER_GREEN_S: 100
ROOMBA6_LOWER_GREEN_V: 50
ROOMBA6_UPPER_GREEN_H: 100
ROOMBA6_UPPER_GREEN_S: 230
ROOMBA6_UPPER_GREEN_V: 100
ROOMBA6_LOWER_ORANGE_H: 10
ROOMBA6_LOWER_ORANGE_S: 80
ROOMBA6_LOWER_ORANGE_V: 120
ROOMBA6_UPPER_ORANGE_H: 20
ROOMBA6_UPPER_ORANGE_S: 200
ROOMBA6_UPPER_ORANGE_V: 200
ROOMBA6_LOWER_PURPLE_H: 110
ROOMBA6_LOWER_PURPLE_S: 80
ROOMBA6_LOWER_PURPLE_V: 40
ROOMBA6_UPPER_PURPLE_H: 150
ROOMBA6_UPPER_PURPLE_S: 230
ROOMBA6_UPPER_PURPLE_V: 100
