ROOMBA4_LOWER_RED_H: 130
ROOMBA4_LOWER_RED_S: 180
ROOMBA4_LOWER_RED_V: 80
ROOMBA4_UPPER_RED_H: 180
ROOMBA4_UPPER_RED_S: 230
ROOMBA4_UPPER_RED_V: 180
ROOMBA4_LOWER_BLUE_H: 95
ROOMBA4_LOWER_BLUE_S: 210
ROOMBA4_LOWER_BLUE_V: 40
ROOMBA4_UPPER_BLUE_H: 110
ROOMBA4_UPPER_BLUE_S: 255
ROOMBA4_UPPER_BLUE_V: 180
ROOMBA4_LOWER_YELLOW_H: 20
ROOMBA4_LOWER_YELLOW_S: 120
ROOMBA4_LOWER_YELLOW_V: 90
ROOMBA4_UPPER_YELLOW_H: 40
ROOMBA4_UPPER_YELLOW_S: 210
ROOMBA4_UPPER_YELLOW_V: 255
ROOMBA4_LOWER_GREEN_H: 60
ROOMBA4_LOWER_GREEN_S: 100
ROOMBA4_LOWER_GREEN_V: 50
ROOMBA4_UPPER_GREEN_H: 100
ROOMBA4_UPPER_GREEN_S: 230
ROOMBA4_UPPER_GREEN_V: 100
ROOMBA4_LOWER_ORANGE_H: 10
ROOMBA4_LOWER_ORANGE_S: 80
ROOMBA4_LOWER_ORANGE_V: 120
ROOMBA4_UPPER_ORANGE_H: 20
ROOMBA4_UPPER_ORANGE_S: 200
ROOMBA4_UPPER_ORANGE_V: 200
ROOMBA4_LOWER_PURPLE_H: 110
ROOMBA4_LOWER_PURPLE_S: 80
ROOMBA4_LOWER_PURPLE_V: 40
ROOMBA4_UPPER_PURPLE_H: 150
ROOMBA4_UPPER_PURPLE_S: 230
ROOMBA4_UPPER_PURPLE_V: 100
