TOLERANCE: 0.2
MIN_CLUSTER_SIZE: 5
MAX_CLUSTER_SIZE: 10000
# windowsのペイントでHだけ180/255をかける
LOWER_RED_H: 150
LOWER_RED_S: 150
LOWER_RED_V: 200
UPPER_RED_H: 190
UPPER_RED_S: 255
UPPER_RED_V: 255

LOWER_BLUE_H: 10
LOWER_BLUE_S: 150
LOWER_BLUE_V: 170
UPPER_BLUE_H: 30
UPPER_BLUE_S: 260
UPPER_BLUE_V: 220

LOWER_YELLOW_H: 22
LOWER_YELLOW_S: 40
LOWER_YELLOW_V: 100
UPPER_YELLOW_H: 30
UPPER_YELLOW_S: 120
UPPER_YELLOW_V: 200

LOWER_GREEN_H: 60 # 60
LOWER_GREEN_S: 60 # 100
LOWER_GREEN_V: 60 # 95
UPPER_GREEN_H: 85 # 80
UPPER_GREEN_S: 180 # 180
UPPER_GREEN_V: 250 # 190

LOWER_WHITE_H: 5
LOWER_WHITE_S: 5
LOWER_WHITE_V: 245
UPPER_WHITE_H: 25
UPPER_WHITE_S: 25
UPPER_WHITE_V: 255